services:
  queue:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
      
  workerservice:
    image: workerservice
    build:
      context: .
      dockerfile: WorkerService/Dockerfile
