services:
  queue:
    hostname: rmq
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  
  webapi:
    image: webapi
    build:
      context: ./WebAPI
      dockerfile: ./Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    restart: on-failure
    depends_on:
        - queue
      
  workerservice:
    image: workerservice
    build:
      context: ./WorkerService
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
        - queue
